theme: jekyll-theme-cayman
title: Copilot Booster
description: Run multiple Copilot agents in parallel. One taskbar icon to manage them all.
url: https://rogerbarreto.github.io
baseurl: /copilot-booster
image: https://rogerbarreto.github.io/copilot-booster/images/logo.png
plugins:
  - jekyll-seo-tag
